# Generated by Django 6.0.2 on 2026-06-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_auth', '0002_userdashboard_customgroup_customgroupmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Guest'), (1, 'Student'), (2, 'Parent'), (3, 'Tutor'), (4, 'Admin'), (999, 'Superadmin')], db_index=True, default=0, verbose_name='role'),
        ),
    ]
