# Generated by Django 6.0.2 on 2026-07-26 05:19

import apps.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_auth', '0004_user_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.auth.models._get_upload_folder, verbose_name='avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
    ]
