# Generated by Django 6.0.2 on 2026-07-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_auth', '0005_remove_user_avatar_url_user_avatar_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=15, null=True, verbose_name='gender'),
        ),
    ]
