from django.urls import path
from . import views

urlpatterns = [
     path("subjects/", views.SubjectListApiView.as_view(), name="subject-list"),
     path("", views.CourseListApiView.as_view(), name="course-list"),
     path("<int:pk>/", views.CourseDetailApiView.as_view(),
          name="course-detail"),
     path("<int:course_id>/apply-tags/", views.ApplyCourseTagsAPIView.as_view(),
          name="course-apply-tags"),
     path("chapters/", views.ChapterListApiView.as_view(),
          name="chapter-list"),
     path("chapters/<int:pk>/", views.ChapterDetailApiView.as_view(),
          name="chapter-detail"),
     path("chapters/reorder/", views.ChapterReorderApiView.as_view(),
          name="chapter-reorder"),
     path("lessons/", views.LessonListApiView.as_view(),
          name="lesson-list"),
     path("lessons/<int:pk>/", views.LessonDetailApiView.as_view(),
          name="lesson-detail"),
     path("lessons/reorder/", views.LessonReorderApiView.as_view(),
          name="lesson-reorder"),
     path("items/", views.ItemListApiView.as_view(),
          name="item-list"),
     path("items/reorder/", views.ItemReorderApiView.as_view(),
          name="item-reorder"),
     path("items/grouped/", views.ItemGroupedApiView.as_view(),
          name="item-grouped"),
     path("items/<int:pk>/", views.ItemDetailApiView.as_view(),
          name="item-detail"),
     path("upload/initiate/", views.InitiateMultipartUploadView.as_view(),
          name="upload-initiate"),
     path("upload/complete/", views.CompleteMultipartUploadView.as_view(),
          name="upload-complete"),
     path("upload/abort/", views.AbortMultipartUploadView.as_view(),
          name="upload-abort"),
     path("items/<int:item_id>/progress/", views.ItemProgressApiView.as_view(),
          name="item-progress"),
     path("items/user-progress/", views.UserLatestItemProgress.as_view(),
               name="item-progress"),
     path("daily-quiz/", views.DailyQuizStatusView.as_view(),
          name="daily-quiz-status"),
     path("daily-quiz/start/", views.StartDailyQuizView.as_view(),
          name="daily-quiz-start"),
     path("daily-quiz/questions/", views.DailyQuizQuestionListView.as_view(),
          name="daily-quiz-question-list"),
     path("daily-quiz/questions/list/", views.DailyQuizGradeSummaryView.as_view(),
          name="daily-quiz-grade-summary"),
     path("daily-quiz/questions/upload/", views.DailyQuizQuestionUploadView.as_view(),
          name="daily-quiz-question-upload"),
     path("daily-quiz/questions/<int:question_id>/", views.DailyQuizQuestionDetailView.as_view(),
          name="daily-quiz-question-detail"),
     path("daily-quiz/<int:quiz_id>/answer/", views.SubmitDailyQuizAnswerView.as_view(),
          name="daily-quiz-answer"),
     path("daily-quiz/<int:quiz_id>/results/", views.DailyQuizResultsView.as_view(),
          name="daily-quiz-results"),
     path("items/<int:item_id>/quiz/", views.QuizItemView.as_view(),
          name="item-quiz"),
     path("items/<int:item_id>/quiz/questions/", views.QuizQuestionListView.as_view(),
          name="item-quiz-questions"),
     path("items/<int:item_id>/quiz/questions/upload/", views.QuizQuestionUploadView.as_view(),
          name="item-quiz-questions-upload"),
     path("items/<int:item_id>/quiz/questions/<int:question_id>/", views.QuizQuestionDetailView.as_view(),
          name="item-quiz-question-detail"),
     path("items/<int:item_id>/quiz/start/", views.StartQuizAttemptView.as_view(),
          name="item-quiz-start"),
     path("quiz-attempts/<int:attempt_id>/answer/", views.SubmitQuizAnswerView.as_view(),
          name="quiz-attempt-answer"),
     path("quiz-attempts/<int:attempt_id>/results/", views.QuizResultsView.as_view(),
          name="quiz-attempt-results"),
]
