# Generated by Django 6.0.2 on 2026-06-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'session_dashboard',
                'verbose_name_plural': 'session_dashboards',
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
