# Generated by Django 6.0.2 on 2026-08-10 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms_course', '0004_chapter_is_free_preview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterMathAIMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mathai_lesson_id', models.CharField(blank=True, default='', help_text='External Math AI lesson_id representing this chapter (see the lessons array under GET /api/external/v1/subjects/{id}). Leave blank if not yet mapped.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mathai_mapping', to='lms_course.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMathAIMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mathai_subject_id', models.CharField(help_text='External Math AI subject_id representing this course (see GET /api/external/v1/subjects).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mathai_mapping', to='lms_course.course')),
            ],
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('course', 'Course'), ('lesson', 'Chapter')], default='global', max_length=10)),
                ('mathai_subject_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mathai_lesson_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mathai_chat_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_chat_threads', to='lms_course.chapter')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_chat_threads', to='lms_course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'scope', 'chapter'], name='lms_ai_chat_user_id_fe6f52_idx'), models.Index(fields=['user', 'scope', 'course'], name='lms_ai_chat_user_id_af7c6d_idx')],
            },
        ),
    ]
