# Generated by Django 6.0.2 on 2026-08-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_ai_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiChatDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ai_chat_dashboard',
                'verbose_name_plural': 'ai_chat_dashboards',
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
