# Generated by Django 6.0.2 on 2026-08-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoints',
            name='grade_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
