# flake8: noqa

"""
Django settings for lms project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
from celery.schedules import crontab
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") in ["True", "1", 1]

ALLOWED_HOSTS = [host.lower().strip() for host in os.getenv("ALLOWED_HOSTS").split(",")]
CSRF_TRUSTED_ORIGINS = [host.lower().strip() for host in os.getenv("CSRF_TRUSTED_ORIGINS").split(",")]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "parler",
    "taggit",
    "apps.auth",
    "apps.course",
    "apps.sessions",
    "apps.billing",
    "apps.leaderboard",
    "apps.ai_chat",
    "django_cleanup.apps.CleanupConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "lms.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lms.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DJANGO_ENV = os.getenv("DJANGO_ENV", "development")

if DJANGO_ENV == "production":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": os.getenv("POSTGRES_HOST", "localhost"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


AUTH_USER_MODEL = "lms_auth.User"

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = [
    ("en", _("English")),
    ("my", _("Burmese")),
]

PARLER_LANGUAGES = {
    None: [{"code": language[0]} for language in LANGUAGES],
    "default": {
        "fallbacks": ["my", "en"],
        "hide_untranslated": False,
    },
}

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = str(BASE_DIR / os.getenv("STATIC_ROOT"))

MEDIA_URL = "media/"
MEDIA_ROOT = str(BASE_DIR / os.getenv("MEDIA_ROOT"))


REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": None,
    "JWT_AUTH_HTTPONLY": False,
    "TOKEN_MODEL": None,
}


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_RATES": {
        "otp_verify": "10/min",
        "otp_request": "10/hour",
        "channel_lookup": "30/hour",
    },
}

JWT_AUTH_COOKIE = None


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("ACCESS_TOKEN_LIFETIME_DAYS", 1)),
        hours=int(os.getenv("ACCESS_TOKEN_LIFETIME_HOURS", 0)),
        minutes=int(os.getenv("ACCESS_TOKEN_LIFETIME_MINUTES", 0)),
        seconds=int(os.getenv("ACCESS_TOKEN_LIFETIME_SECONDS", 0)),
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.getenv("REFRESH_TOKEN_LIFETIME_DAYS", 7)),
        hours=int(os.getenv("REFRESH_TOKEN_LIFETIME_HOURS", 0)),
        minutes=int(os.getenv("REFRESH_TOKEN_LIFETIME_MINUTES", 0)),
        seconds=int(os.getenv("REFRESH_TOKEN_LIFETIME_SECONDS", 0)),
    ),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "UPDATE_LAST_LOGIN": True,
}

# Settings for drf-spectacular (OpenAPI schema + docs)
SPECTACULAR_SETTINGS = {
    "TITLE": os.getenv("SPECTACULAR_TITLE", "MathMentor API"),
    "DESCRIPTION": os.getenv("SPECTACULAR_DESCRIPTION", "MathMentor API schema"),
    "VERSION": os.getenv("SPECTACULAR_VERSION", "1.0.0"),
}

CORS_ALLOWED_ORIGINS = [
    host.lower().strip() for host in os.getenv("CORS_ALLOWED_ORIGINS").split(",")
]

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")

EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS") in [True, "True", 1, "1"]
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")

CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

CELERY_BEAT_SCHEDULE = {
    "sweep-expired-enrollments": {
        "task": "apps.billing.tasks.sweep_expired_enrollments",
        "schedule": crontab(hour=0, minute=5),
    },
}

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_S3_BUCKET_NAME = os.getenv("AWS_S3_BUCKET_NAME")
AWS_S3_REGION = os.getenv("AWS_S3_REGION", "us-east-1")
CLOUDFRONT_DOMAIN = os.getenv("CLOUDFRONT_DOMAIN", "")  # e.g. d1234abcdef.cloudfront.net

# Daily.co
DAILY_API_KEY = os.getenv("DAILY_API_KEY", "")
DAILY_DOMAIN = os.getenv("DAILY_DOMAIN", "")
DAILY_API_BASE_URL = os.getenv("DAILY_API_BASE_URL", "https://api.daily.co/v1")
DAILY_WEBHOOK_SECRET = os.getenv("DAILY_WEBHOOK_SECRET", "")

# Dinger payment gateway
DINGER_CLIENT_ID = os.getenv("DINGER_CLIENT_ID", "")
DINGER_SECRET_KEY = os.getenv("DINGER_SECRET_KEY", "")
DINGER_PUBLIC_KEY = os.getenv("DINGER_PUBLIC_KEY", "")
DINGER_ENCRYPTION_KEY = os.getenv("DINGER_ENCRYPTION_KEY", "")
DINGER_API_KEY = os.getenv("DINGER_API_KEY", "")
DINGER_CALLBACK_KEY = os.getenv("DINGER_CALLBACK_KEY", "")
DINGER_BASE_URL = os.getenv("DINGER_BASE_URL", "")
DINGER_DEV_CALLBACK = os.getenv("DINGER_DEV_CALLBACK", "False") == "True"

# Math AI ("LuLu AI") third-party tutoring service
MATHAI_API_BASE_URL = os.getenv("MATHAI_API_BASE_URL", "").rstrip("/")
MATHAI_API_KEY = os.getenv("MATHAI_API_KEY", "")

# SMSPoh SMS gateway (used for phone-based OTP delivery)
SMSPOH_BASE_URL = os.getenv("SMSPOH_BASE_URL", "https://v3.smspoh.com/api/rest")
SMSPOH_API_KEY = os.getenv("SMSPOH_API_KEY", "")
SMSPOH_API_SECRET = os.getenv("SMSPOH_API_SECRET", "")
SMSPOH_SENDER_ID = os.getenv("SMSPOH_SENDER_ID", "SMSPoh")
SMS_DISABLE = os.getenv("SMS_DISABLE", "False") in ["True", "1", 1, True]
