# Generated by Django 6.0.2 on 2026-07-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_course', '0003_coursedashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_free_preview',
            field=models.BooleanField(default=False),
        ),
    ]
