# Generated by Django 6.0.2 on 2026-08-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_course', '0004_chapter_is_free_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
